### ISSUE TITLE
Update stable version in repo to 0.2.0

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.luxtronik1#18]
# Think about update stable version to 0.2.0
**Version**: stable=**0.1.0** (104 days old) => latest=**0.2.0** (55 days old)
**Installs**: stable=**19** (55.88%), latest=**6** (17.65%), total=**34**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L685)

**Comment by forelleblau** [comment]
done
